<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_START</name>
   <tag></tag>
   <elementGuidId>3913f16e-0d4f-43b0-ad9d-98e556551647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdcbfdc0-ac9f-47ab-b0a6-48c769ecee35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>246b5161-2ed2-4151-b3a4-10233dc64209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>a3935a76-cf12-4ee4-8453-933907423954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aca2bd80-bb44-4b3a-a249-921fe40b737f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea08225c-67ce-440d-9ffd-c8fdcf046e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href ='/Registration/Home/Trademark' </value>
      <webElementGuid>1e362242-e184-46a9-99b9-007a3f0baf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START</value>
      <webElementGuid>40451bf7-7fdc-43e9-bdd7-739c5a1719ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnStart&quot;)</value>
      <webElementGuid>7efa26dd-d783-4bbd-9fae-0897544b5d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnStart']</value>
      <webElementGuid>322d774d-ac0e-4ed1-b14d-e6d6349dbe21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='column1']/div/div[6]/div/button</value>
      <webElementGuid>252eab07-9414-448f-877b-210b8f8b8c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>48ef2752-67c2-44eb-ba18-49fd9d0b69c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnStart' and @name = 'btnStart' and @type = 'submit' and (text() = 'START' or . = 'START')]</value>
      <webElementGuid>f43bc539-0ea6-4e8d-befb-71798d634a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
