<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_element70</name>
   <tag></tag>
   <elementGuidId>48e4c326-4930-4a60-b3e0-6164d373e21b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element70_Trademark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element70_Trademark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e93e7e66-f7a6-4032-9ec6-1cf5c5b12a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ee95c71c-3c77-4df0-beab-903636f9d08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Trademark</value>
      <webElementGuid>bfba633e-0ed0-4d1f-afe3-ed8035160961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element70_Trademark</value>
      <webElementGuid>c2844cea-27d5-44ca-b850-1d981049dd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>63d1fd9a-dbb7-49dc-bbf7-18e40408a04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>e2eab60c-867d-4803-bccf-128572f4f004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck form-element-wrapper radio-button requiredCustom align-block add-to-repository condition-trigger</value>
      <webElementGuid>da132f6a-c6db-4a05-b2b9-413efa537c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4.1</value>
      <webElementGuid>79ceff67-274b-4ee8-8061-51f5589b00b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>d57b2b9a-f4cf-42af-ab12-b345721a0193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1388392c-a75b-4c1d-ad8c-41e274120c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Check the appropriate field: Trademark or Service Mark</value>
      <webElementGuid>c2275ea9-660d-4c56-9849-e650c161f7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>826d2fe2-1204-4bea-a4c6-09cdf30c0c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-10</value>
      <webElementGuid>c3c83d10-cbb1-4b63-b2e0-0a760d0a6a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element70_Trademark&quot;)</value>
      <webElementGuid>48ca97d8-0d74-490e-b0c8-70c861a9d9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_Registration_01/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>c6694500-75a2-4305-b17d-ad80279d469b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element70_Trademark']</value>
      <webElementGuid>0fb4153a-70dc-411b-8605-d0c13479336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_70']/div/div[2]/div/fieldset/div/div/input</value>
      <webElementGuid>6bc123f2-755b-48cf-952f-bcd35c6a02e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>f3570928-2a85-4a27-9a19-f598d039e2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'element70_Trademark' and @name = 'element70']</value>
      <webElementGuid>091dee96-d879-4f7d-9791-fb5e4023d3c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
