<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b</name>
   <tag></tag>
   <elementGuidId>213d67b5-2b39-474f-b294-9d9af35ff24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s2id_element13 > span.selection > span.select2-selection.select2-selection--single > span.select2-selection__arrow > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='s2id_element13']/span/span/span[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>0cce0eb2-3a28-48b0-b46f-6846e71a7788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>854c8c09-4d14-4c94-8d96-6e890a872a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_element13&quot;)/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]/span[@class=&quot;select2-selection__arrow&quot;]/b[1]</value>
      <webElementGuid>171054cd-ebd7-4a95-8311-463a15db4f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_Registration_02/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>12855f98-9ac7-4617-8fe0-d6a2db655e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='s2id_element13']/span/span/span[2]/b</value>
      <webElementGuid>b7d16bf1-e365-4652-988b-7d05213f977a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div[2]/div/span/span/span/span[2]/b</value>
      <webElementGuid>60eb4952-e886-4162-a464-f1a62ae76771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
