<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_element447</name>
   <tag></tag>
   <elementGuidId>6619e3a2-c8c0-47fe-9a81-53cadc80a2c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element447</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element447']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e069681-c332-4b7c-8529-dae57db2c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2986f447-26c1-4d74-9165-0edb5a5e93c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9c1d5de3-c6c0-47a9-86f7-108f839ba2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck requiredCustom input-text textfield  show-character-count tooltipstered</value>
      <webElementGuid>f375d034-7664-4511-a8be-720f0b92ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element447</value>
      <webElementGuid>5133b708-a7d2-4d2b-bef9-6b9569d89a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element447</value>
      <webElementGuid>ed97d305-ff81-4134-bad5-d420c28e344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>584529f7-ff94-4be9-b65e-61493d694b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element447</value>
      <webElementGuid>c80156f2-3d99-49ed-917c-d4cd1b44484b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>ad7ac8be-78d5-46c7-9c74-555e311912bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>cac40569-954f-4085-8143-b754b3954b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ddfcde93-e335-42b8-9b40-aacac28cc053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31a5e89b-d685-4a83-ba88-5b41429c4695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Enter your zip</value>
      <webElementGuid>ddefa7b6-1069-4403-b192-8f97df72c426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbe77db6-53b2-429e-b609-e47b72801723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8446576e-48b8-485b-8734-c5e02cfb4546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element447&quot;)</value>
      <webElementGuid>fe8a4c36-5563-4e60-8664-7ab22d697748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_Registration_02/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>5a36f3b0-26ab-45f0-8041-2bffb12121e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element447']</value>
      <webElementGuid>32c810ba-9092-47c4-a228-186949a88b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_447']/div/div[2]/input</value>
      <webElementGuid>f9593596-4ba7-4fbc-966a-9eaf0d0f08df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/input</value>
      <webElementGuid>eec3cf6c-06dc-4ef8-aed5-cb5375c60dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'element447' and @name = 'element447' and @type = 'text']</value>
      <webElementGuid>633c20c1-1733-47f4-9abd-3330a2865d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
