<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_element327</name>
   <tag></tag>
   <elementGuidId>fed67927-9cf2-4df2-8035-3c4ede1e27b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element327</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element327']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7645ead8-0595-4ade-9e2b-82e80af681ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5dcfc433-ddf8-46a8-85ea-3612b052052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e3d7cda5-02c3-47cd-8254-353e369e261f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck requiredCustom input-text textfield </value>
      <webElementGuid>322af282-9957-4f76-beea-b4372171883f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element327</value>
      <webElementGuid>ba261cbb-5e60-492f-b6c5-a2972082f604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element327</value>
      <webElementGuid>19b31d49-4487-4702-93ed-3fe9fefb568e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b019f483-356f-4931-ac86-58de64bda74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element327</value>
      <webElementGuid>007ab715-8fac-4547-8d8c-fbb8c952f6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your full name</value>
      <webElementGuid>dc76a908-8395-432c-8af1-8f6a2ff35ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>666bbd81-eecf-4257-84d2-12917436fa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>43fd84fb-e056-47d5-aae4-9f639339a304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e6b88c2-20cb-496e-b54f-4bee654f795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Type your full name</value>
      <webElementGuid>704427d3-ed7b-4ee4-8bca-3dca79509ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0ad56c0-b716-4360-afb7-f129d21743d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_tabindex</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>efee8d71-03b9-4ed0-be09-8c1200a10d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-28</value>
      <webElementGuid>47cca6ea-c066-410c-852b-f376f6f9521f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element327&quot;)</value>
      <webElementGuid>b6e38280-7bcf-43c2-85df-b0e3749312c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_Registration_02/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>8ef02fc8-cd93-4f27-9198-51c582126227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element327']</value>
      <webElementGuid>2f683d36-fbaf-4f03-9dee-2a217eb9199b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_327']/div/div[2]/input</value>
      <webElementGuid>31a9cbb8-dbb5-435b-ab72-19d9fa7fc16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[2]/input</value>
      <webElementGuid>40d64837-ba95-48cf-88ac-5cfac21f4fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'element327' and @name = 'element327' and @placeholder = 'Type your full name' and @type = 'text']</value>
      <webElementGuid>2a235b6f-4725-4225-a5d0-d7f9af1eb458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
