<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_element445</name>
   <tag></tag>
   <elementGuidId>90bdc17c-4194-41fb-821f-fdf8ee76c404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element445</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element445']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>857ea77a-484e-4126-97a7-87fe84a2f9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62098a45-3e77-4362-b409-2b6000edf63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2902d25c-de5e-4148-9aab-cdb3ae5b5980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck requiredCustom input-text textfield  show-character-count tooltipstered</value>
      <webElementGuid>2d155e9b-70c9-4e19-893b-b0b6099a23b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element445</value>
      <webElementGuid>02e3b6eb-1f93-4c89-8078-03ffc5134b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element445</value>
      <webElementGuid>a525109c-2d59-42d6-8850-68838f829b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>774f44c5-4dec-4872-b3d3-21e60fdf596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element445</value>
      <webElementGuid>791a2268-eece-4857-8718-960c4e0e29c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>1e079500-f341-4082-a0f2-a743fdc7e5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>9d1e1d6a-fbc8-4f4d-9efe-4a4ac7144815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e9a8c448-8b02-44d4-b19c-4052f1b3089e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8a6a0fb-cc97-483e-82a7-8ed8a61d0924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Enter your state</value>
      <webElementGuid>e7db9006-7f6b-4a65-ab47-cdb9651beebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f810bf3-e85d-4893-8413-998905ccd34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_tabindex</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>95502317-388c-4a55-81e3-48f937b51231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element445&quot;)</value>
      <webElementGuid>526bb921-a666-4514-8741-846b0e4e7e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_Registration_02/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>5e2e9141-e110-4e88-a2c6-c03bace4d38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element445']</value>
      <webElementGuid>33b610e4-6da1-4049-a4e9-bfda701737d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_445']/div/div[2]/input</value>
      <webElementGuid>02d0ba43-ebe3-42e9-a4fb-2ca153278c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>06d7a440-d49b-43fc-b0fb-b34dd6a703a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'element445' and @name = 'element445' and @type = 'text']</value>
      <webElementGuid>2f400c38-60ed-4ce1-9154-1cfb868936a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
